In [2]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
from tkinter import messagebox


ruta = 'D:/RAYERE/Documents/Descargas/excelesPrueba/'
#messagebox.showinfo("Ruta",ruta)

contenido = os.listdir(ruta) #listado de archivos en Ruta 
archExceles = []
for fichero in contenido:
    if os.path.isfile(os.path.join(ruta,fichero)) and fichero.endswith('.xlsx'):  #obtener datos tipo excel
        archExceles.append(fichero)
        print(fichero)
        inicio=fichero.find('_')
        final=fichero.find('.')
        print(fichero[7:final])
        archivo = ruta+fichero
        miArch=pd.read_excel(archivo)  # leer archivos
        archAgrupado=miArch.groupby(['Representante'],as_index=False).count() #agrupar
        archPrev=archAgrupado[['Representante','Linea']]   #crear archivo                       
        archPrev.to_csv(ruta+fichero[7:final]+".csv")   #crea csv

    else: 
        messagebox.ERROR()
        
messagebox.showinfo("Resultado","Se han creado los archivos de informacion")

    

listadoFarmacias_19052023.xlsx
Farmacias_19052023
listadoFarmacias_19052023_2.xlsx
Farmacias_19052023_2
listadoMedicos_19052023.xlsx
Medicos_19052023
listadoMedicos_19052023_2.xlsx
Medicos_19052023_2


'ok'

In [2]:
import numpy as np

# Crear el arreglo original
arreglo_original = np.arange(21).reshape(7, 3)
print("Arreglo original:\n", arreglo_original)

# Repetir el arreglo 3 veces
arreglo_repetido = np.tile(arreglo_original, (2, 1))
print("Arreglo repetido:\n", arreglo_repetido)


Arreglo original:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]
Arreglo repetido:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]


In [17]:
import numpy as np
import pandas as pd

productos = np.array([
    ["P1001", "P1002", "P1003"],
    ["P2001", "P2002", "P2003"],
    ["P3001", "P3002", "P3003"]
])

repres = np.array([
    ["P1201", "Angel"],
    ["P1202", "Erica"]
])

productos_con_columnas_adicionales = np.repeat(productos, len(repres), axis=0)
repres_repetido = np.tile(repres, (len(productos), 1))

productos_con_columnas_adicionales = np.concatenate((productos_con_columnas_adicionales, repres_repetido), axis=1)


print(productos_con_columnas_adicionales)

midataframe=pd.DataFrame(productos_con_columnas_adicionales)

midataframe.to_excel("miexcel.xlsx")


[['P1001' 'P1002' 'P1003' 'P1201' 'Angel']
 ['P1001' 'P1002' 'P1003' 'P1202' 'Erica']
 ['P2001' 'P2002' 'P2003' 'P1201' 'Angel']
 ['P2001' 'P2002' 'P2003' 'P1202' 'Erica']
 ['P3001' 'P3002' 'P3003' 'P1201' 'Angel']
 ['P3001' 'P3002' 'P3003' 'P1202' 'Erica']]


In [5]:
import pandas as pd
import numpy as np

path="D:/RAYERE/Documents/Investigacion de Mercados/2023/Material X Ciclo/CICLO 6/"
rutasRep = pd.read_excel(path+"TABCICLO6.xlsx",sheet_name="RUTA REP")
Materiales = pd.read_excel(path+"TABCICLO6.xlsx",sheet_name="Materiales")
 
productos= Materiales.to_numpy()
#productos

repres=rutasRep.to_numpy()



productos_con_columnas_adicionales = np.repeat(productos, len(repres), axis=0)
repres_repetido = np.tile(repres, (len(productos), 1))

productos_con_columnas_adicionales = np.concatenate((productos_con_columnas_adicionales, repres_repetido), axis=1)

print("------------productos con columnas adicionales--------")
print(productos_con_columnas_adicionales)

midataframe=pd.DataFrame(productos_con_columnas_adicionales)

midataframe.to_excel(path+"miexcel.xlsx")



[['VALGION' 'AYUDA VISUAL VALGION CLT' 'MP' 1
  'P1201 Roberto Herrera Cervantes' 'REP 1']
 ['VALGION' 'AYUDA VISUAL VALGION CLT' 'MP' 1
  'P1202 Luís Arturo Rodríguez Páramo' 'REP 2']
 ['VALGION' 'AYUDA VISUAL VALGION CLT' 'MP' 1
  'P1204 Erica Milena Bastida Jimenez' 'REP 3']
 ...
 ['DUOFLEX' 'DUOFLEX TABLETA 200 mg/50 mg C/30 ORIGINAL' 'MM' 40
  'P1803 Beatriz Adriana Quezada García' 'REP 40']
 ['DUOFLEX' 'DUOFLEX TABLETA 200 mg/50 mg C/30 ORIGINAL' 'MM' 40
  'P1904 Nadia Mireya Pérez Ayala ' 'REP 41']
 ['DUOFLEX' 'DUOFLEX TABLETA 200 mg/50 mg C/30 ORIGINAL' 'MM' 40
  'P1905 José Nolazco Cota' 'REP 42']]
